name: ci

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
      #   name: Build and test
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     target: test
      #     load: true
      - 
        name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - 
        name: Print tag version
        run: echo ${{ steps.get_version.outputs.VERSION }}
        run: echo ${{ github.ref }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          build-args: |
            "TEST_TOKEN=${{ 123456 }}"
            "TAG_VERSION=${{ steps.get_version.outputs.VERSION }}"